"""empty message

Revision ID: 493f31c7ea08
Revises: 70ccdaa14f4b
Create Date: 2023-01-15 05:23:34.863332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '493f31c7ea08'
down_revision = '70ccdaa14f4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_books', sa.Column('title', sa.String(), nullable=True))
    op.add_column('user_books', sa.Column('authors', sa.String(), nullable=True))
    op.drop_column('user_books', 'book')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_books', sa.Column('book', sa.VARCHAR(), nullable=True))
    op.drop_column('user_books', 'authors')
    op.drop_column('user_books', 'title')
    # ### end Alembic commands ###
