"""empty message

Revision ID: 88eeea31cebb
Revises: 5fcd7b61bbb4
Create Date: 2023-01-18 01:34:24.786777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88eeea31cebb'
down_revision = '5fcd7b61bbb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_libraries', sa.Column('short', sa.String(), nullable=True))
    op.add_column('user_libraries', sa.Column('formal', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_libraries', 'formal')
    op.drop_column('user_libraries', 'short')
    # ### end Alembic commands ###
