"""empty message

Revision ID: d565b334f05c
Revises: e78e64a397f1
Create Date: 2023-01-28 04:06:58.713692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd565b334f05c'
down_revision = 'e78e64a397f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommended_books', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommended_books', 'updated_at')
    # ### end Alembic commands ###
