"""empty message

Revision ID: e78e64a397f1
Revises: 5edaea312e66
Create Date: 2023-01-24 23:18:14.218521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e78e64a397f1'
down_revision = '5edaea312e66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_books', sa.Column('isbn', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_books', 'isbn')
    # ### end Alembic commands ###
